### ISSUE TITLE
READMEのメンテナンス性を向上させることができていない

### ISSUE THREAD

**Issue by Yuisei-Maruyama** [Yuisei-Maruyama/MyPortfolio#128]
現在、 README は 

- root直下の`README.md`
- `documents/README.md`

の **2箇所** に存在する。

上記 **2箇所** に `documents/README.md` を記載している理由としては、
`tsx` ファイルから root 直下のREADMEファイルのパスを読み込む良い手段が見つからないために  
やむを得ず作成した。  

しかし、上記の2ファイルをメンテナンスするのはコストが高く、記述し忘れることも多々ある。  

なので、  
コミットが走ったタイミングで root 直下のREADMEを `documents/README.md` に複製する形を考える。

**Comment by Yuisei-Maruyama** [comment]
## Cannot use import statement outside a module 対策

README の複製を行うスクリプトの作成を行う中で、  

`npx ts-node XXX`  を実行して、スクリプトを実行するのだが  
下記のエラーに遭遇した。

```ts
MyPortfolio yuisei_rock$ npx ts-node duplicateReadme.ts
(node:61783) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/yuisei_rock/Desktop/aaa/MyPortfolio/duplicateReadme.ts:1
import { readFileSync } from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module.m._compile (/Users/yuisei_rock/Desktop/aaa/MyPortfolio/node_modules/ts-node/src/index.ts:1459:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yuisei_rock/Desktop/aaa/MyPortfolio/node_modules/ts-node/src/index.ts:1462:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/Users/yuisei_rock/Desktop/aaa/MyPortfolio/node_modules/ts-node/src/bin.ts:389:12)
    at Object.<anonymous> (/Users/yuisei_rock/Desktop/aaa/MyPortfolio/node_modules/ts-node/src/bin.ts:539:3)
```

**Comment by Yuisei-Maruyama** [comment]
## Cannot use import statement outside a module 対策

そこで、root直下に `tools`ディレクトリを作成し、その配下に `package.json` を新たに作成し、
その中に { "type": "modules" } とだけ記述することで解決した。  

(tools/package.json)
```ts
{ "type": "modules" }
```

(ディレクトリ構成)
```ts
./
+- package.json (書き換えたくない)
`- tools/
   +- index.ts (対象のファイル)
   `- package.json (これを追加する)
```

**Comment by Yuisei-Maruyama** [comment]
## fsモジュールの`readFileSync`を使用したファイル読み込みについて

下記のような状態であった場合に root 直下の `README.md` を読み込みたいとする。

```ts
├── tools
│   ├── duplicateReadme.ts <- このファイルでREADME.md を読み込みたい
│   ├── loadPackage.ts
│   ├── package.json
│   └── tsconfig.json
├── README.md
```

そのような場合、作業ディレクトリからのパスではなく、**fsはパスを作業ディレクトリ**  から辿る！！！  
上記の作業ディレクトリとは、 **nodeを実行したファイルがあるディレクトリ** のことを指す。

例えば、`MyPortfolio`  の階層で node を実行しようとする。

```ts
── MyPortfolio  <- ここで node を実行している
    ├── README.md
    ├── src
    ├── tools
    │   ├── duplicateReadme.ts
    │   ├── loadPackage.ts
    │   ├── package.json
    │   └── tsconfig.json
```

上記の例であれば、`readFileSync` のパスは

(duplicateReadme.ts)
```ts
const readme = readFileSync('README.md', 'utf8')  // 正しく読み込める
const readme = readFileSync('。。・README.md', 'utf8')  // no such file or directory, open になる
```
